name: Deploy Redoc to GitHub Pages

on:
  push:
    branches: [main]

  # 手動実行できるようにするための指定
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Build
        run: npm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: public
  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
