# name: Deploy Redoc to GitHub Pages

# on:
#   push:
#     branches: [main]

#   # 手動実行できるようにするための指定
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           ref: main

#       - name: Setup node
#         uses: actions/setup-node@v2
#         with:
#           node-version: "18"

#       - name: Build
#         run: npm run build

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./public
